export const SIGNED_IN = 'SIGNED_IN';
export const PASSING_BOOK_DATA = 'PASSING_BOOK_DATA';
export const GET_PAYMENT_METHOD = 'GET_PAYMENT_METHOD';
export const FORM_MODE = 'FORM_MODE';
export const TABLE_STATE = 'TABLE_STATE';